# Generated by Django 5.2 on 2025-04-13 06:31

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='challenge',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='full_description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='results',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='solution',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
