# Generated by Django 5.2 on 2025-04-13 06:31

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
