# Generated by Django 5.2 on 2025-04-13 06:31

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='about_full',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='mission',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='values',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='vision',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=tinymce.models.HTMLField(),
        ),
    ]
